id: P010793
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4035
  title: མདོ་སྡེ་བསྐལ་པ་བཟང་པོ།
  author: ''
  volumes:
    52b0a37c4deb44acb6fad167918c832d:
      image_group_id: I3CN4175
      title: ''
      volume_number: 1
      total_pages: 944
      base_file: v001.txt
