id: I0B959DB7
legacy_id: P010793
ocr_import_info:
  bdrc_scan_id: W3CN4035
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:48:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:18:05.749793+00:00'
last_modified: 2022-09-03 22:18:31.795479
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4035
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4035
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་སྡེ་བསྐལ་པ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.705299935581337
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I3CN4175:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4175
      total_pages: 944
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4175.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.705299935581337
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
